// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ie6rb-nn-oS0Yl9aWT84tF-oEOdQDaU',
    appId: '1:929956541628:web:270b74a6278de3bc4b0cb9',
    messagingSenderId: '929956541628',
    projectId: 'live-match-update',
    authDomain: 'live-match-update.firebaseapp.com',
    storageBucket: 'live-match-update.firebasestorage.app',
    measurementId: 'G-PQXBHF1BYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyhCkUuTlyIXnH9Ml2HnZJaS0o3grzdUo',
    appId: '1:929956541628:android:db3705c6bc97de1d4b0cb9',
    messagingSenderId: '929956541628',
    projectId: 'live-match-update',
    storageBucket: 'live-match-update.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFgEN_AD9QasupqXFzsvy1E-YJEs6hXQ',
    appId: '1:929956541628:ios:6fbaf2670822abca4b0cb9',
    messagingSenderId: '929956541628',
    projectId: 'live-match-update',
    storageBucket: 'live-match-update.firebasestorage.app',
    iosBundleId: 'com.example.liveMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFgEN_AD9QasupqXFzsvy1E-YJEs6hXQ',
    appId: '1:929956541628:ios:6fbaf2670822abca4b0cb9',
    messagingSenderId: '929956541628',
    projectId: 'live-match-update',
    storageBucket: 'live-match-update.firebasestorage.app',
    iosBundleId: 'com.example.liveMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3ie6rb-nn-oS0Yl9aWT84tF-oEOdQDaU',
    appId: '1:929956541628:web:b08447bddb42bd014b0cb9',
    messagingSenderId: '929956541628',
    projectId: 'live-match-update',
    authDomain: 'live-match-update.firebaseapp.com',
    storageBucket: 'live-match-update.firebasestorage.app',
    measurementId: 'G-K8B3XXLKCH',
  );
}
